# Generated by Django 4.0.4 on 2022-06-23 14:59

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('answer__created_at'), descending=True, nulls_first=True), '-created_at']},
        ),
    ]
